# Generated by Django 5.1.3 on 2024-12-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('previa', 'Diagnóstica'), ('final', 'Final')], max_length=10)),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('diagnostica', 'Diagnóstica'), ('final', 'Final')], max_length=15)),
            ],
        ),
    ]
