# Generated by Django 5.1.3 on 2024-12-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('previa', 'Previa'), ('final', 'Final')], max_length=10)),
                ('puntaje', models.IntegerField()),
                ('observaciones', models.TextField()),
            ],
        ),
    ]
