# Generated by Django 5.1.3 on 2024-12-09 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluaciones', '0001_initial'),
        ('experimentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='experimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentos.experimento'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='experimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='experimentos.experimento'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='preguntas',
            field=models.ManyToManyField(related_name='evaluaciones', to='evaluaciones.pregunta'),
        ),
    ]
