# Generated by Django 5.1.3 on 2024-12-02 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('materiales', models.TextField()),
                ('procedimiento', models.TextField()),
                ('fecha', models.DateField()),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.contenido')),
            ],
        ),
    ]
