# Generated by Django 5.1.3 on 2024-12-09 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experimentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experimento',
            name='asignado_a',
            field=models.ManyToManyField(related_name='experimentos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experimento',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimentos_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
