# Generated by Django 5.1.3 on 2024-12-05 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimento',
            name='estudiantes',
        ),
        migrations.AddField(
            model_name='experimento',
            name='asignado_a',
            field=models.ManyToManyField(related_name='experimentos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experimento',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experimento',
            name='materiales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experimento',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experimento',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimentos_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
