# Generated by Django 5.1.3 on 2024-12-09 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0002_initial'),
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimento',
            name='horario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experimento_asignado', to='horarios.horario'),
        ),
    ]
