# Generated by Django 5.1.3 on 2024-12-09 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0003_experimento_horario'),
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='experimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_relacionados', to='experimentos.experimento'),
        ),
    ]
